
name: Build-Deploy

on: [pull_request]


jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - name: Build
        run: npx nx affected:build
